[theme]
# Color principal (botones, acentos) - Un verde oscuro corporativo
primaryColor = "#004C91"

# Color de fondo general de la aplicación
backgroundColor = "#F8FAFD"

# Color de fondo secundario (barra lateral, algunos widgets)
secondaryBackgroundColor = "#E9EEF5"

# Color del texto principal
textColor = "#0E1117"

# Fuente de la aplicación (opcional, deja vacío para la fuente por defecto)
# font = "sans serif" 

font = "sans serif"
